services:
  - type: web
    name: after-school-lessons-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: afterSchoolApp
          property: connectionString